In [1]:
import tensorflow as tf
tf.executing_eagerly() # Check if eager execution is enabled

True

In [2]:
x = [[10.]]
res = tf.matmul(x, x)
print(res)

tf.Tensor([[100.]], shape=(1, 1), dtype=float32)


In [3]:
a = tf.constant([[10,20], [30,40]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [4]:
b = tf.add(a, 2)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 22],
       [32, 42]])>

In [5]:
print(a * b)

tf.Tensor(
[[ 120  440]
 [ 960 1680]], shape=(2, 2), dtype=int32)


In [7]:
m = tf.Variable([4.0, 5.0, 6.0], tf.float32, name='m')
c = tf.Variable([1.0, 1.0, 1.0], tf.float32, name='c')

In [8]:
m, c # Initialization of variables happens right away in eager execution mode

(<tf.Variable 'm:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>,
 <tf.Variable 'c:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)

In [9]:
x = tf.Variable([100.0, 100.0, 100.0], tf.float32, name='x')
x

<tf.Variable 'x:0' shape=(3,) dtype=float32, numpy=array([100., 100., 100.], dtype=float32)>

In [10]:
y = m * x + c
y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([401., 501., 601.], dtype=float32)>

In [11]:
def tensorflow(max_num):

    counter = tf.constant(0)
    max_num = tf.constant(max_num)

    for num in range(0, max_num.numpy() + 1):
        num = tf.constant(num)

        if int(num % 3) == 0 and int(num % 5) == 0:
            print(f'Divisible by 3 and 5: {num.numpy()}')
        elif int(num % 3) == 0:
            print(f'Divisible by 3: {num.numpy()}')
        elif int(num % 5) == 0:
            print(f'Divisible by 5: {num.numpy()}')
        else:
            print(f'{num.numpy()}')
        counter += 1

In [12]:
tensorflow(15)

Divisible by 3 and 5: 0
1
2
Divisible by 3: 3
4
Divisible by 5: 5
Divisible by 3: 6
7
8
Divisible by 3: 9
Divisible by 5: 10
11
Divisible by 3: 12
13
14
Divisible by 3 and 5: 15
